# Generated by Django 6.0.3 on 2026-07-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/thumbs/'),
        ),
    ]
