from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_repair_store_schema"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE shop_product ADD COLUMN IF NOT EXISTS discount_percent integer NOT NULL DEFAULT 0;

            CREATE TABLE IF NOT EXISTS shop_wishlist (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at timestamp with time zone NOT NULL DEFAULT now(),
                product_id bigint NOT NULL REFERENCES shop_product(id) DEFERRABLE INITIALLY DEFERRED,
                user_id integer NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE (user_id, product_id)
            );

            CREATE TABLE IF NOT EXISTS shop_productreview (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                rating smallint NOT NULL,
                comment text NOT NULL,
                created_at timestamp with time zone NOT NULL DEFAULT now(),
                product_id bigint NOT NULL REFERENCES shop_product(id) DEFERRABLE INITIALLY DEFERRED,
                user_id integer NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE (product_id, user_id)
            );

            CREATE INDEX IF NOT EXISTS shop_wishlist_product_id_idx ON shop_wishlist(product_id);
            CREATE INDEX IF NOT EXISTS shop_wishlist_user_id_idx ON shop_wishlist(user_id);
            CREATE INDEX IF NOT EXISTS shop_productreview_product_id_idx ON shop_productreview(product_id);
            CREATE INDEX IF NOT EXISTS shop_productreview_user_id_idx ON shop_productreview(user_id);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
